= How to add Jolt JNI to an existing project
:experimental:
:JPH: Jolt Physics
:JPHAdj: Jolt-Physics
:page-pagination:
:Project: Jolt JNI
:url-enwiki: https://en.wikipedia.org/wiki
:url-tutorial: https://github.com/stephengold/jolt-jni-docs/blob/master/java-apps/src/main/java/com/github/stephengold/sportjolt/javaapp/sample

Adding {Project} to an existing project is a 10-step process:

. Add libraries to the classpath.
. Load the native library.
. Register memory allocators and install callbacks.
. Create a factory and register the standard types.
. Create a temporary allocator and a job system.
. Define 2 kinds of collision layers (object and broadphase),
   the mapping from object layers to broadphase layers,
   and the collision filters for layers.
. Create and configure a physics system.
. Create and configure physics objects and add them to the physics system.
. Simulate the physics system.
. Test and tune as necessary.


== Add libraries to classpath

{Project} requires both a JVM library and a native library.
Both kinds of libraries are available pre-built from Maven Central.

Build types:  use "Debug" native libraries for development and troubleshooting,
then switch to "Release" native libraries for performance testing and production.

Flavors:  use "Dp" native libraries to simulate large worlds
(>10 km in diameter) otherwise use "Sp".

=== Android projects

{Project} comes pre-built for Android as a pair of AARs (one for each build type).
Each AAR includes both a JVM library and all necessary native libraries.

I suggest starting out with the Debug-type AAR.
Add to the relevant "build.gradle" or "build.gradle.kts" file:

[source,groovy]
----
repositories {
    mavenCentral()
}
dependencies {
    implementation(
            group: "com.github.stephengold",
            name: "jolt-jni-Android",
            version: "3.4.0",
            classifier: "SpDebug",
            ext: "aar"
    )
}
----

=== Gradle-built desktop projects

{Project} comes pre-built for desktops as a platform-independent JVM library
plus a set of (separately-packaged) native libraries.

Because of how releases are built,
each desktop JVM library is released under 8 distinct names (artifact IDs)
that can be used interchangeably.
In contrast, each desktop native library is specific to a particular platform,
build type, and flavor.

I suggest starting with a JVM library
plus the "DebugSp" native library for your development environment.
For a "Linux on x86_64" environment,
add to the relevant "build.gradle" or "build.gradle.kts" file:

[source,groovy]
----
repositories {
    mavenCentral()
}
dependencies {
    // JVM library:
    implementation("com.github.stephengold:jolt-jni-Windows64:3.4.0")

    // native libraries:
    runtimeOnly("com.github.stephengold:jolt-jni-Linux64:3.4.0:DebugSp")
        // Native libraries for other platforms also could be added.
}
----

* For a 64-bit MS-Windows environment, replace "Linux64" with "Windows64".
* For an "Apple silicon" MacOS environment, replace "Linux64" with "MacOSX_ARM64".


== Load the native library

You must load {Project}'s native library
before instantiating any physics objects.

=== Android projects

Add to your physics initialization:

[source,java]
----
System.loadLibrary("joltjni");
----

=== Desktop projects

The https://github.com/Electrostat-Lab/jSnapLoader[JSnapLoader library]
may be used for this purpose.
Add to the relevant "build.gradle" or "build.gradle.kts" file:

[source,groovy]
----
dependencies {
    implementation("io.github.electrostat-lab:snaploader:1.1.1-stable")
    runtimeOnly("com.github.oshi:oshi-core:6.9.0")
}
----

Add to your physics initialization:

[source,java]
----
import electrostatic4j.snaploader.LibraryInfo;
import electrostatic4j.snaploader.LoadingCriterion;
import electrostatic4j.snaploader.NativeBinaryLoader;
import electrostatic4j.snaploader.filesystem.DirectoryPath;
import electrostatic4j.snaploader.platform.NativeDynamicLibrary;
import electrostatic4j.snaploader.platform.util.PlatformPredicate;

// ...

LibraryInfo info = new LibraryInfo(null, "joltjni", DirectoryPath.USER_DIR);
NativeBinaryLoader loader = new NativeBinaryLoader(info);

NativeDynamicLibrary[] libraries = {
        new NativeDynamicLibrary("linux/aarch64/com/github/stephengold", PlatformPredicate.LINUX_ARM_64),
        new NativeDynamicLibrary("linux/armhf/com/github/stephengold", PlatformPredicate.LINUX_ARM_32),
        new NativeDynamicLibrary("linux/x86-64/com/github/stephengold", PlatformPredicate.LINUX_X86_64),
        new NativeDynamicLibrary("osx/aarch64/com/github/stephengold", PlatformPredicate.MACOS_ARM_64),
        new NativeDynamicLibrary("osx/x86-64/com/github/stephengold", PlatformPredicate.MACOS_X86_64),
        new NativeDynamicLibrary("windows/x86-64/com/github/stephengold", PlatformPredicate.WIN_X86_64)
};
loader.registerNativeLibraries(libraries).initPlatformLibrary();
loader.loadLibrary(LoadingCriterion.CLEAN_EXTRACTION);
----


== Memory allocators and callbacks

To avoid the need to explicitly close `JoltPhysicsObject` instances,
I recommend starting {Project}'s built-in cleaner thread,
which frees objects automatically during JVM garbage collection.

{JPH} allows custom allocators for native heap memory.
For simplicity, I recommend registering the default allocator:

[source,java]
----
import com.github.stephengold.joltjni.Jolt;
import com.github.stephengold.joltjni.JoltPhysicsObject;

// ...

JoltPhysicsObject.startCleaner(); // to free Jolt-Physics objects automatically
Jolt.registerDefaultAllocator(); // tell Jolt Physics to use malloc/free
----

{JPH} allows custom callbacks for native assertions and trace output.
I recommend starting with the default callbacks,
which print to the standard output:

[source,java]
----
Jolt.installDefaultAssertCallback();
Jolt.installDefaultTraceCallback();
----

[NOTE]
====
In Release-type native libraries, assertions are disabled,
so `installDefaultAssertCallback()` is a no-op.
====


== Create factory and register types

{JPH} uses a factory object to create instances of classes
based on their name or hash,
for instance when deserializing saved data.

Once the factory is created,
you should register all the standard types
and install their collision handlers:

[source,java]
----
boolean success = Jolt.newFactory();
assert success;
Jolt.registerTypes();
----


== Temporary allocator and job system

{JPH} needs a `TempAllocator` to allocate temporary memory
during simulation.
Since it's difficult to predict how much temporary memory will be needed,
I recommend using `TempAllocatorMalloc`, the most flexible implementation.

[source,java]
----
import com.github.stephengold.joltjni.TempAllocator;
import com.github.stephengold.joltjni.TempAllocatorMalloc;

// ...

TempAllocator tempAllocator = new TempAllocatorMalloc();
----

Similarly, {JPH} needs a `JobSystem` to assign simulation tasks to processors.
Since it's difficult to predict how many jobs and barriers will be needed,
I suggest using the default limits,
even though they may be larger than needed.
For now, I assume you'll want to use all available processors:

[source,java]
----
import com.github.stephengold.joltjni.JobSystem;
import com.github.stephengold.joltjni.JobSystemThreadPool;

// ...

int numWorkerThreads = Runtime.getRuntime().availableProcessors();
JobSystem jobSystem = new JobSystemThreadPool(
        Jolt.cMaxPhysicsJobs, Jolt.cMaxPhysicsBarriers, numWorkerThreads);
----


== Collision layers

{JPH} allows you to organize bodies into _collision layers_
and specify which layers may collide.
It's typical to put moving and non-moving bodies
into separate layers
and specify that non-moving bodies collide only with moving bodies,
not with other non-moving bodies.

Each body belongs to an _object layer_, defaulting to layer 0.
You can define up to 65,536 object layers.

Collision layers can be defined both for objects and broadphase:

* _broadphase layers_ are used during broad-phase detection, and
* _object layers_ are used during narrow-phase detection.

The sole limitation is that there must be a consistent mapping
from object layers to broadphase layers.

For now, I suggest putting moving and non-moving bodies
into separate object layers
and mapping both object layers to broadphase layer 0:

[source,java]
----
final int numBpLayers = 1;

final int numObjLayers = 2;
final int objLayerMoving = 0;
final int objLayerNonMoving = 1;

ObjectLayerPairFilterTable ovoFilter
        = new ObjectLayerPairFilterTable(numObjLayers);
// Enable collisions between 2 moving bodies:
ovoFilter.enableCollision(objLayerMoving, objLayerMoving);
// Enable collisions between a moving body and a non-moving one:
ovoFilter.enableCollision(objLayerMoving, objLayerNonMoving);
// Disable collisions between 2 non-moving bodies:
ovoFilter.disableCollision(objLayerNonMoving, objLayerNonMoving);

// Map both object layers to broadphase layer 0:
BroadPhaseLayerInterfaceTable layerMap
        = new BroadPhaseLayerInterfaceTable(numObjLayers, numBpLayers);
layerMap.mapObjectToBroadPhaseLayer(objLayerMoving, 0);
layerMap.mapObjectToBroadPhaseLayer(objLayerNonMoving, 0);
/*
 * Pre-compute the rules for colliding object layers
 * with broadphase layers:
 */
ObjectVsBroadPhaseLayerFilterTable ovbFilter
        = new ObjectVsBroadPhaseLayerFilterTable(
                layerMap, numBpLayers, ovoFilter, numObjLayers);
----

For further advice regarding collision layers, see
https://jrouwe.github.io/JoltPhysics/index.html#collision-detection[the collision-detection section of the {JPHAdj} documentation].


== Create a physics system

As soon as you create a `PhysicsSystem`, you should configure it
to the expected number of number of bodies, mutexes, body pairs, and contacts.
In many cases, it's difficult to predict how many resources will be needed,
so I suggest setting these limits fairly high:

[source,java]
----
PhysicsSystem physicsSystem = new PhysicsSystem();

int maxBodies = 5_000;
int numBodyMutexes = 0; // 0 means "use the default number"
int maxBodyPairs = 65_536;
int maxContacts = 20_480;
physicsSystem.init(maxBodies, numBodyMutexes, maxBodyPairs, maxContacts,
        layerMap, ovbFilter, ovoFilter);
----


== Add physics objects

_Physics objects_ include:

* bodies (`Body`)
** rigid bodies
** soft bodies
* constraints (`Constraint`)
** vehicles (`VehicleConstraint`)
* characters (`CharacterBase`)

This tutorial starts with rigid bodies.

Body creation begins with a `BodyCreationSettings` object, which can be reused.
Here's a code fragment that creates a spherical rigid body:

[source,java]
----
// Create a collision shape:
float ballRadius = 0.3f;
ConstShape ballShape = new SphereShape(ballRadius);

// Create and configure body-creation settings:
BodyCreationSettings bcs = new BodyCreationSettings();
bcs.setShape(ballShape);

// Create a rigid body for a specific PhysicsSystem:
BodyInterface bi = physicsSystem.getBodyInterface();
Body ball = bi.createBody(bcs);
----

A body isn't simulated unless added to its physics system.
Use `BodyInterface.addBody()`:

[source,java]
----
bi.addBody(ball, EActivation.Activate);
----


== Simulate the physics system

To simulate a single 20-millisecond step:

[source,java]
----
float timePerStep = 0.02f; // in seconds
int numCollisionSteps = 1;
physicsSystem.update(
        timePerStep, numCollisionSteps, tempAllocator, jobSystem);
----


== HelloJoltJni

{url-tutorial}/console/HelloJoltJni.java[HelloJoltJni]
is a complete console app (no graphics)
that serves as a starting point for running {Project}.

It illustrates:

. loading a native library
. creating a `PhysicsSystem`
. creating 2 bodies and adding them to the physics system
. simulating 50 steps

[IMPORTANT]
====
`HelloJoltJni` is the first in a series of
tutorial apps designed for hands-on learning.
I expect you to not only study the source code,
but to actually run the app as well.
Take time *now* to set up a
{url-enwiki}/Integrated_development_environment[software development environment]
for this purpose!

For instance, if you install Git and a Java Development Kit,
you should be able to launch tutorial apps from a command shell, like so:

. `git clone https://github.com/stephengold/jolt-jni-docs.git`
. `cd jolt-jni-docs`
. `./gradlew :java-apps:HelloJoltJni`
====


== Summary

* Two libraries are required: a JVM library and a native library.
* You can organize bodies into layers and specify which layers collide.
* Physics objects aren't simulated unless they're added to a physics system.
