= Jolt-JNI project overview
:Cplusplus: C&#43;&#43;
:JPH: Jolt Physics
:JPHAdj: Jolt-Physics
:Project: Jolt JNI
:ProjectAdj: Jolt-JNI
:url-enwiki: https://en.wikipedia.org/wiki

_{Project}_ is a {url-enwiki}/Physics_engine[physics-simulation] library
for {url-enwiki}/List_of_JVM_languages[JVM languages]
such as {url-enwiki}/Java_(programming_language)[Java],
{url-enwiki}/Python_(programming_language)[Python],
{url-enwiki}/JavaScript[JavaScript],
{url-enwiki}/Kotlin_(programming_language)[Kotlin],
{url-enwiki}/Apache_Groovy[Groovy], and
{url-enwiki}/Scala_(programming_language)[Scala].

Use it to:

* add solidity to architecture, characters, projectiles, terrain, and vehicles,
* detect collisions between complex shapes,
* perform contact, ray, and sweep tests,
* simulate characters and buildings collapsing in real time, and
* simulate cloth, rope, and deformable volumes,
  including their interactions with rigid bodies.

Tutorials and sample apps are provided to help you get started.

All software in the {ProjectAdj} project is free and open-source,
including the JVM library, the native libraries, the demo and tutorial apps,
and the software used to build, test, and run them.

The underlying simulation software comes from
https://jrouwe.github.io/JoltPhysics[_{JPH}_], a modern, thread-aware physics simulator.
But although {JPH} is written in {url-enwiki}/C%2B%2B[{Cplusplus}],
you won't need any knowledge of {Cplusplus} to use {Project}.

{Project} also incorporates source code from
https://github.com/kmammou/v-hacd[the V-HACD project].


== Caveats

{Project}'s focus is on simulating
{url-enwiki}/Classical_mechanics[classical mechanics]
in just enough detail to add verisimilitude to 3-D games.
It's not intended for 2-D {url-enwiki}/Platform_game[platformers],
nor for scientific research.
For 2-D physics, consider using http://www.dyn4j.org/[dyn4j] instead.

{Project} and its documentation
assume a certain level of proficiency with
{url-enwiki}/Java_(programming_language)[the Java programming language].
The project isn't aimed at non-programmers,
nor developers without prior Java experience.
Similarly, it assumes familiarity with vector math and 3-D computer graphics.

While an understanding of classical mechanics is assumed,
many of its technical terms are linked (at first use)
to the relevant article in the English Wikipedia.

{Project} requires Java version 11 or higher.

https://raw.githubusercontent.com/stephengold/jolt-jni/master/LICENSE[The project's open-source license]
disclaims liability for defects.
Please don't use this software in safety-critical applications.


== What's missing

Current limitations gated by {JPH}:

+ {Project} doesn't simulate collisions between soft bodies,
  nor self collisions within soft bodies.
  See https://github.com/jrouwe/JoltPhysics/issues/789[{JPHAdj} issue 789].
+ {Project} doesn't simulate anisotropic friction.
  See https://github.com/jrouwe/JoltPhysics/issues/1216[{JPHAdj} issue 1216].
+ Aside from buoyancy and drag on rigid objects,
  {Project} doesn't simulate fluid dynamics.

Also, {Project} doesn't yet run on every known platform.
In particular, native libraries aren't provided for AIX, FreeBSD, iOS,
LoongArch, PowerPC, RISCV, 32-bit Windows, or Window-on-ARM.
These limitations aren't inherent to {Project};
they're gated by access to test hardware.

Furthermore, {JPH} is a large project,
and {Project} doesn’t yet provide access to all its features.
(Its goal is utility, not completeness.)
Feature requests are welcome, and can be submitted via
https://github.com/stephengold/jolt-jni/issues[the issue tracker].


== Getting help

For self-help, utilize
xref:add.adoc[the tutorials],
https://stephengold.github.io/jolt-jni-docs/javadoc/latest/com.github.stephengold.joltjni/com/github/stephengold/joltjni/package-summary.html[the javadoc], and
https://github.com/stephengold/jolt-jni[the source code].

For further reading there is also
https://jrouwe.github.io/JoltPhysics/index.html[the official {JPHAdj} documentation].

For issues that are best handled privately, contact me by e-mail.
My personal e-mail address appears at the bottom
of https://stephengold.github.io/[my homepage] and in the source code.

I welcome suggestions concerning the future development of {Project}.


== Next steps

If you're curious how {Project} works,
proceed to xref:implementation.adoc[the Implementation page].

To gain hands-on experience,
proceed to xref:add.adoc[the first tutorial page].
